title: "Max Base"
description: "@github developer maintainer. Full-Time Open-Sourcerer. Full-stack programmer. In the path of a real computer engineer... (Compiler enthusiast)"
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jemoji

collections:
  networks:
    output: true
    sidebar_label: Networks
#   drafts:
#     output: true
#     sidebar_label: Drafts
#   workshops:
#     output: true
#     sidebar_label: Workshops

jekyll_admin:
  hidden_links:
    - staticfiles
    - datafiles
    - configuration
  homepage: "posts"

exclude:
  - .all-contributorsrc
  - .editorconfig
  - .github
  - .gitignore
  - .jekyll-cache
  - .pre-commit-config.yaml
  - CODEOWNERS
  - codespell.txt
  - demo1.jpg
  - demo2.jpg
  - Gemfile
  - Gemfile.lock
  - vendor
  - server
  - super-linter.report
